/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.4/userguide/building_swift_projects.html in the Gradle documentation.
 */

rootProject.name = "AnnUlitina"
include("koticki.controller")
include("koticki.service")
include("koticki.dal")
include("banks-core")
include("banks-console")
include("koticki")

findProject(":AnnUlitina:koticki:controller")?.name = "controller"
findProject(":AnnUlitina:koticki:service")?.name = "service"
findProject(":AnnUlitina:koticki:dal")?.name = "dal"

findProject(":AnnUlitina:Lab1:banks-core")?.name = "banks-core"
findProject(":AnnUlitina:Lab1:banks-console")?.name = "banks-console"
include("Lab1")
include("koticki")
include("Lab1:banks-core")
findProject(":Lab1:banks-core")?.name = "banks-core"
include("Lab1:banks-console")
findProject(":Lab1:banks-console")?.name = "banks-console"
include("koticki:controller")
findProject(":koticki:controller")?.name = "controller"
include("koticki:dal")
findProject(":koticki:dal")?.name = "dal"
include("koticki:service")
findProject(":koticki:service")?.name = "service"
include("koticki-5")
include("koticki-5:cats")
findProject(":koticki-5:cats")?.name = "cats"
include("koticki-5:owners")
findProject(":koticki-5:owners")?.name = "owners"
include("koticki-5:api-gateway")
findProject(":koticki-5:api-gateway")?.name = "api-gateway"
include("koticki-5:api-gateway:api-gateway-app")
findProject(":koticki-5:api-gateway:api-gateway-app")?.name = "api-gateway-app"
include("koticki-5:api-gateway:security")
findProject(":koticki-5:api-gateway:security")?.name = "security"
include("koticki-5:cats:cats-app")
findProject(":koticki-5:cats:cats-app")?.name = "cats-app"
include("koticki-5:cats:cats-client")
findProject(":koticki-5:cats:cats-client")?.name = "cats-client"
include("koticki-5:cats:cats-model")
findProject(":koticki-5:cats:cats-model")?.name = "cats-model"
include("koticki-5:owners:owners-app")
findProject(":koticki-5:owners:owners-app")?.name = "owners-app"
include("koticki-5:owners:owners-client")
findProject(":koticki-5:owners:owners-client")?.name = "owners-client"
include("koticki-5:owners:owners-model")
findProject(":koticki-5:owners:owners-model")?.name = "owners-model"
include("koticki-5:shared")
findProject(":koticki-5:shared")?.name = "shared"
include("koticki-5:config")
findProject(":koticki-5:config")?.name = "config"
include("koticki-5:shared:messaging")
findProject(":koticki-5:shared:messaging")?.name = "messaging"
include("koticki-5:shared:config")
findProject(":koticki-5:shared:config")?.name = "config"
